# fly.toml app configuration file generated for sheppakai-budget on 2025-12-11T19:28:03-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sheppakai-budget'
primary_region = 'yyz'

[build]

# [deploy]
#   release_command = "npx drizzle-kit migrate"

[[mounts]]
  source = 'sheppakai_budget_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"     # How long to wait for the app to start
    interval = "30s"       # How often to check
    method = "get"
    path = "/api/healthz"  # The URL we created above
    timeout = "5s"         # Max time allowed for a response

[processes]
  app = "./start.sh"
  
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
